version: '2'
services:
  transcoder:
    build: .
    image: vilsol/transcoder
    #restart: always
    tty: true
    volumes:
      - "C:\\Users\\Vilsol\\Documents\\Docker\\TestTranscode:/media"
    environment:
      - "BOT_KEY=${BOT_KEY}"
      - "CHAT_ID=${CHAT_ID}"
      - "HOST=${HOST}"